services:
  - type: web
    name: fz-bypass-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: OWNER_ID
        sync: false
      - key: AUTH_CHATS
        sync: false
      - key: GOFILE_API_KEY
        sync: false
      - key: GOFILE_API_TOKEN
        sync: false
      - key: SOLVER_API
        value: https://solver-production-fbc1.up.railway.app
      - key: BYPASS_PROXY_POOL
        sync: false
