services:
  - type: web
    name: fz-bypass-bot
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python bot.py
    plan: starter
    disk:
      name: fz-chromium-profile
      mountPath: /opt/render/project/src/.cache/ms-playwright
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: OWNER_ID
        sync: false
      - key: AUTH_CHATS
        sync: false
      - key: GOFILE_API_KEY
        sync: false
      - key: GOFILE_API_TOKEN
        sync: false
      - key: CHROMIUM_PROFILE_DIR
        value: /tmp/chromium-profile
      - key: CHROMIUM_PATH
        value: /usr/bin/chromium
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/.cache/ms-playwright
      - key: SOLVER_API
        value: https://turnstile-solver-production-7e59.up.railway.app
      - key: BYPASS_PROXY_POOL
        sync: false