services:
  - type: web
    name: fz-bypass-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    disk:
      name: fz-chromium-profile
      mountPath: /tmp/chromium-profile
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: OWNER_ID
        sync: false
      - key: AUTH_CHATS
        sync: false
      - key: GOFILE_API_KEY
        sync: false
      - key: GOFILE_API_TOKEN
        sync: false
      - key: CHROMIUM_PROFILE_DIR
        value: /tmp/chromium-profile
      - key: CHROMIUM_PATH
        value: /usr/bin/chromium
      - key: SOLVER_API
        value: https://turnstile-solver-production-7e59.up.railway.app
      - key: BYPASS_PROXY_POOL
        sync: false
